### ISSUE TITLE
Not Run at AdminLTE Versi 2

### ISSUE THREAD

**Issue by erycamel** [ruliarmando/yiisms#1]
![err](https://cloud.githubusercontent.com/assets/606654/12016857/aeed6b18-ad82-11e5-8785-ebd2620e7242.png)

**Comment by ruliarmando** [comment]
problem nya apa ya gan @erycamel ???

detail environment nya gimana (os, php, apache, etc) ?

**Comment by erycamel** [comment]
Om, saya copy AdminLTE versi 2 (dari directory "AdminLTE-2.3.2/dist") , ke directory Web....
Hasilnya Seperti gambar diatas....

OS: Windows 7, xampp-win32-7.0.0-0-VC14.7z

**Comment by ruliarmando** [comment]
bisa jadi tidak cocok dengan admin lte v2, perbedaan css atau letak asset  nya mungkin, soalnya saya kan develop dengan admin lte v1
